server:
  port: 9999
spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
    open-in-view: true
  datasource:
    url: jdbc:postgresql://127.0.0.1:5454/minfin-db?autoreconnect=true
    username: minfin
    password: minfin

  profiles:
    active: minfin
